cfg = {'norm_cfg': {'type': 'SyncBN', 'requires_grad': True}, 
        'data_preprocessor': {'type': 'DualInputSegDataPreProcessor', 
                              'mean': [123.675, 116.28, 103.53, 123.675, 116.28, 103.53], 
                              'std': [58.395, 57.12, 57.375, 58.395, 57.12, 57.375], 
                              'bgr_to_rgb': True, 
                              'size_divisor': 32, 
                              'pad_val': 0, 
                              'seg_pad_val': 255, 
                              'test_cfg': {'size_divisor': 32}}, 
        'model': {'type': 'DIEncoderDecoder', 
                  'data_preprocessor': {'type': 'DualInputSegDataPreProcessor', 
                                        'mean': [123.675, 116.28, 103.53, 123.675, 116.28, 103.53], 
                                        'std': [58.395, 57.12, 57.375, 58.395, 57.12, 57.375], 
                                        'bgr_to_rgb': True, 
                                        'size_divisor': 32, 
                                        'pad_val': 0, 
                                        'seg_pad_val': 255, 
                                        'test_cfg': {'size_divisor': 32}}, 
                    'pretrained': None, 
                    'backbone': {'type': 'IA_ResNetV1c', 
                                 'depth': 18, 
                                 'num_stages': 4, 
                                 'out_indices': (0, 1, 2, 3), 
                                 'dilations': (1, 1, 1, 1), 
                                 'strides': (1, 2, 2, 2), 
                                 'norm_cfg': {'type': 'SyncBN', 
                                              'requires_grad': True}, 
                                'norm_eval': False, 
                                'style': 'pytorch', 
                                'contract_dilation': True, 
                                'interaction_cfg': (None, {'type': 'SpatialExchange', 'p': 0.5}, 
                                                        {'type': 'ChannelExchange', 'p': 0.5}, 
                                                        {'type': 'ChannelExchange', 'p': 0.5})}, 
                    'decode_head': {'type': 'Changer', 
                                    'in_channels': [64, 128, 256, 512], 
                                    'in_index': [0, 1, 2, 3], 
                                    'channels': 128, 
                                    'dropout_ratio': 0.1, 
                                    'num_classes': 2, 
                                    'norm_cfg': {'type': 'SyncBN', 
                                                 'requires_grad': True}, 
                                    'align_corners': False, 
                                    'loss_decode': {'type': 'mmseg.CrossEntropyLoss', 
                                                    'use_sigmoid': False, 
                                                    'loss_weight': 1.0}, 
                                    'sampler': {'type': 'mmseg.OHEMPixelSampler', 
                                                'thresh': 0.7, 
                                                'min_kept': 100000}}, 
                    'train_cfg': {}, 
                    'test_cfg': {'mode': 'whole'}}, 
        'default_scope': 'opencd', 
        'env_cfg': {'cudnn_benchmark': True, 
                    'mp_cfg': {'mp_start_method': 'fork', 
                               'opencv_num_threads': 0}, 
                    'dist_cfg': {'backend': 'nccl'}}, 
        'vis_backends': [{'type': 'CDLocalVisBackend'}], 
        'visualizer': {'type': 'CDLocalVisualizer', 
                       'vis_backends': [{'type': 'CDLocalVisBackend'}], 
                       'name': 'visualizer', 
                       'alpha': 1.0, 
                       'save_dir': 'tmp_infer_tif'}, 
        'log_processor': {'by_epoch': False}, 
        'log_level': 'INFO', 
        'load_from': 'changer_r18_s2looking_workdir/iter_80000.pth', 
        'resume': False, 
        'tta_model': {'type': 'mmseg.SegTTAModel'}, 
        'dataset_type': 'S2Looking_Dataset', 
        'data_root': 'data/100_', 
        'crop_size': (512, 512), 
        'train_pipeline': [{'type': 'MultiImgLoadImageFromFile'}, 
                           {'type': 'MultiImgLoadAnnotations'}, 
                           {'type': 'MultiImgRandomRotFlip', 'rotate_prob': 0.5, 'flip_prob': 0.5, 'degree': (-20, 20)}, 
                           {'type': 'MultiImgRandomCrop', 'crop_size': (512, 512), 'cat_max_ratio': 0.75}, 
                           {'type': 'MultiImgExchangeTime', 'prob': 0.5}, 
                           {'type': 'MultiImgPhotoMetricDistortion', 'brightness_delta': 10, 'contrast_range': (0.8, 1.2), 'saturation_range': (0.8, 1.2), 'hue_delta': 10}, 
                           {'type': 'MultiImgPackSegInputs'}], 
        'test_pipeline': [{'type': 'MultiImgLoadImageFromFile'}, 
                          {'type': 'MultiImgResize', 'scale': (1024, 1024), 'keep_ratio': True}, 
                          {'type': 'MultiImgLoadAnnotations'}, 
                          {'type': 'MultiImgPackSegInputs'}], 
        'img_ratios': [0.75, 1.0, 1.25], 
        'tta_pipeline': [{'type': 'MultiImgLoadImageFromFile', 'backend_args': None}, 
                         {'type': 'TestTimeAug', 
                          'transforms': [[{'type': 'MultiImgResize', 'scale_factor': 0.75, 'keep_ratio': True}, 
                                          {'type': 'MultiImgResize', 'scale_factor': 1.0, 'keep_ratio': True}, 
                                          {'type': 'MultiImgResize', 'scale_factor': 1.25, 'keep_ratio': True}], 
                                          [{'type': 'MultiImgRandomFlip', 'prob': 0.0, 'direction': 'horizontal'}, 
                                           {'type': 'MultiImgRandomFlip', 'prob': 1.0, 'direction': 'horizontal'}], 
                                           [{'type': 'MultiImgLoadAnnotations'}], 
                                           [{'type': 'MultiImgPackSegInputs'}]]}], 
        'train_dataloader': {'batch_size': 8, 
                             'num_workers': 4, 
                             'persistent_workers': True, 
                             'sampler': {'type': 'InfiniteSampler', 'shuffle': True}, 
                             'dataset': {'type': 'S2Looking_Dataset', 
                                         'data_root': 'data/100_', 
                                         'data_prefix': {'seg_map_path': 'train/label', 
                                                         'img_path_from': 'train/Image1', 
                                                         'img_path_to': 'train/Image2'}, 
                                        'pipeline': [{'type': 'MultiImgLoadImageFromFile'}, 
                                                     {'type': 'MultiImgLoadAnnotations'}, 
                                                     {'type': 'MultiImgRandomRotFlip', 'rotate_prob': 0.5, 'flip_prob': 0.5, 'degree': (-20, 20)}, 
                                                     {'type': 'MultiImgRandomCrop', 'crop_size': (512, 512), 'cat_max_ratio': 0.75}, 
                                                     {'type': 'MultiImgExchangeTime', 'prob': 0.5}, 
                                                     {'type': 'MultiImgPhotoMetricDistortion', 
                                                      'brightness_delta': 10, 
                                                      'contrast_range': (0.8, 1.2), 
                                                      'saturation_range': (0.8, 1.2), 
                                                      'hue_delta': 10}, 
                                                      {'type': 'MultiImgPackSegInputs'}]}}, 
        'val_dataloader': {'batch_size': 1, 
                           'num_workers': 4, 
                           'persistent_workers': True, 
                           'sampler': {'type': 'DefaultSampler', 'shuffle': False}, 
                           'dataset': {'type': 'S2Looking_Dataset', 
                                       'data_root': 'data/100_', 
                                       'data_prefix': {'seg_map_path': 'val/label', 
                                                       'img_path_from': 'val/Image1', 
                                                       'img_path_to': 'val/Image2'}, 
                                        'pipeline': [{'type': 'MultiImgLoadImageFromFile'}, 
                                                     {'type': 'MultiImgResize', 'scale': (1024, 1024), 'keep_ratio': True}, 
                                                     {'type': 'MultiImgLoadAnnotations'}, 
                                                     {'type': 'MultiImgPackSegInputs'}]}}, 
        'test_dataloader': {'batch_size': 1, 
                            'num_workers': 4, 
                            'persistent_workers': True, 
                            'sampler': {'type': 'DefaultSampler', 'shuffle': False}, 
                            'dataset': {'type': 'S2Looking_Dataset', 
                                        'data_root': 'data/100_', 
                                        'data_prefix': {'img_path_from': 'test/Image1', 
                                                        'img_path_to': 'test/Image2'}, 
                                        'pipeline': [{'type': 'MultiImgLoadImageFromFile'}, 
                                                     {'type': 'MultiImgResize', 'scale': (1024, 1024), 'keep_ratio': True}, 
                                                     {'type': 'MultiImgLoadAnnotations'}, 
                                                     {'type': 'MultiImgPackSegInputs'}]}}, 
        'val_evaluator': {'type': 'mmseg.IoUMetric', 
                          'iou_metrics': ['mFscore', 'mIoU']}, 
        'test_evaluator': {'type': 'mmseg.IoUMetric', 
                           'iou_metrics': ['mFscore', 'mIoU']}, 
        'optimizer': {'type': 'AdamW', 
                      'lr': 0.001, 
                      'betas': (0.9, 0.999), 
                      'weight_decay': 0.05}, 
        'optim_wrapper': {'type': 'OptimWrapper', 
                          'optimizer': {'type': 'AdamW', 'lr': 0.001, 'betas': (0.9, 0.999), 'weight_decay': 0.05}}, 
        'param_scheduler': [{'type': 'LinearLR', 'start_factor': 1e-06, 'by_epoch': False, 'begin': 0, 'end': 1000}, 
                            {'type': 'PolyLR', 'power': 1.0, 'begin': 1000, 'end': 80000, 'eta_min': 0.0, 'by_epoch': False}], 
        'train_cfg': {'type': 'IterBasedTrainLoop', 'max_iters': 80000, 'val_interval': 8000}, 
        'val_cfg': {'type': 'ValLoop'}, 
        'test_cfg': {'type': 'TestLoop'}, 
        'default_hooks': {'timer': {'type': 'IterTimerHook'}, 
                          'logger': {'type': 'LoggerHook', 'interval': 50, 'log_metric_by_epoch': False}, 
                          'param_scheduler': {'type': 'ParamSchedulerHook'}, 
                          'checkpoint': {'type': 'CheckpointHook', 'by_epoch': False, 'interval': 8000, 'save_best': 'mIoU'}, 
                          'sampler_seed': {'type': 'DistSamplerSeedHook'}, 
                          'visualization': {'type': 'CDVisualizationHook', 'interval': 1, 'img_shape': (1024, 1024, 3), 'draw': True}}, 
        'launcher': 'none', 'work_dir': './work_dirs\\changer_ex_r18_512x512_80k_s2looking'}